# Site settings
title: eBay MIND Patterns - Accessibility Patterns for the Web
email: ianmcburnie@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  This site contains working examples for all patterns found in the book
  eBay MIND Patterns - Accessibility Patterns for the Web.
baseurl: "/mindpatterns"
url: "http://ianmcburnie.github.io"
patterns_baseurl: "/mindpatterns/"
patterns_url: "https://ebay.gitbook.io"

# twitter_username: ianmcburnie
# github_username:  ianmcburnie

# Build settings
markdown: kramdown

sass:
    style: :compressed

exclude: ["node_modules", "_js", ".cache", ".sass-cache", ".git"]

collections:
- messaging
- input
- navigation
- disclosure

collections:
    messaging:
        output: true
    input:
        output: true
    navigation:
        output: true
    disclosure:
        output: true
